version: 0.2

phases:
  pre_build:
    commands:
      - cd core-services
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - core-services/target/photosalon-api-0.0.1-SNAPSHOT.jar
